version: '3.8'

services:
  app:
    build: .
    container_name: ci-cd-pipeline-demo-app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=mydb
    ports:
      - "8080:8080"
    command: ["node", "app.js"]

  db:
    image: postgres:13
    container_name: ci-cd-pipeline-demo-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    # 🚫 no ports for CI, to avoid conflicts

volumes:
  db_data:
