version: '3.9'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todopass
      POSTGRES_DB: todoapp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: todo
      DB_PASS: todopass
      DB_NAME: todoapp
    ports:
      - "8080:8080"

volumes:
  db_data:

